Controllers/Admin_LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegandLogin.Models;

namespace RegandLogin.Controllers
{
    public class Admin_LoginController : Controller
    {
        practice_purposeEntities db1 = new practice_purposeEntities();

        // GET: Admin_Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Admin objcheck)
        {

            if (ModelState.IsValid)
            {
                using (practice_purposeEntities db1 = new practice_purposeEntities())
                {
                    var obj = db1.Admins.Where(a => a.Admin_Name.Equals(objcheck.Admin_Name) && a.Admin_Password.Equals(objcheck.Admin_Password)).FirstOrDefault();

                    if (obj != null)
                    {
                        Session["Admin_Id"] = obj.Admin_Id.ToString();
                        Session["Admin_Name"] = obj.Admin_Name.ToString();
                        return RedirectToAction("Index", "Admins");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Incorrect UserName or Password");

                    }
                }
            }

            return View(objcheck);

        }
    }
}
    

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegandLogin.Models;

namespace RegandLogin.Controllers
{
    public class LoginController : Controller
    {
        practice_purposeEntities db = new practice_purposeEntities();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(new_User objchk)
        {

            if (ModelState.IsValid)
            {
                using (practice_purposeEntities db = new practice_purposeEntities())
                {
                    var obj = db.new_User.Where(a => a.user_name.Equals(objchk.user_name) && a.Password.Equals(objchk.Password)).FirstOrDefault();

                    if (obj != null)
                    {
                        Session["UserId"] = obj.user_id.ToString();
                        Session["UserName"] = obj.user_name.ToString();
                        return RedirectToAction("Index", "ViewBook");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Incorrect UserName or Password");

                    }
                }
            }

            return View(objchk);
        }
    }
}

Controllers/new_UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RegandLogin.Models;

namespace RegandLogin.Controllers
{
    public class new_UserController : Controller
    {
        private practice_purposeEntities db = new practice_purposeEntities();

        // GET: new_User
        public ActionResult Index()
        {
            return View(db.new_User.ToList());
        }

        // GET: new_User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            new_User new_User = db.new_User.Find(id);
            if (new_User == null)
            {
                return HttpNotFound();
            }
            return View(new_User);
        }

        // GET: new_User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: new_User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user_id,user_name,Password,address,mail,mobile")] new_User new_User)
        {
            if (ModelState.IsValid)
            {
                db.new_User.Add(new_User);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: new_User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            new_User new_User = db.new_User.Find(id);
            if (new_User == null)
            {
                return HttpNotFound();
            }
            return View(new_User);
        }

        // POST: new_User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_id,user_name,Password,address,mail,mobile")] new_User new_User)
        {
            if (ModelState.IsValid)
            {
                db.Entry(new_User).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(new_User);
        }

        // GET: new_User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            new_User new_User = db.new_User.Find(id);
            if (new_User == null)
            {
                return HttpNotFound();
            }
            return View(new_User);
        }

        // POST: new_User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            new_User new_User = db.new_User.Find(id);
            db.new_User.Remove(new_User);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Library Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("User Registration", "Create", "new_User")</li>
                    <li>@Html.ActionLink("Log In", "Index", "Login")</li>
                    <li>@Html.ActionLink("Admin Login", "Index", "Admin_Login")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>